### ISSUE TITLE
Add management endpoints

### ISSUE THREAD

**Issue by jokk-itu** [jokk-itu/authserver#18]
**Description of the feature you want**
Make it possible for people to request for the creation of a client, resource or scope.
Make it possible for client, resource and scope owners to use CRUD operations on said entities.

**Describe the solution you would like**
A controller for each entity.
An endpoint for each CRUD operation (Post, Get, Put, Delete).
A way to request a token to create the entity as a beginning and acquire a token to Get, Put and Delete the entity afterwards.
Implement the feature as according to the specification on Dynamic registration and use its principles on Scope and Resources as well.

- [x] Client Initial Endpoint
- [x] Client Post Endpoint
- [ ] Client Get Endpoint
- [ ] Client Put Endpoint
- [ ] Client Delete Endpoint

- [x] Resource Initial Endpoint
- [x] Resource Post Endpoint
- [ ] Resource Get Endpoint
- [ ] Resource Put Endpoint
- [ ] Resource Delete Endpoint

- [x] Scope Initial Endpoint
- [x] Scope Post Endpoint
- [ ] Scope Get Endpoint
- [ ] Scope Put Endpoint
- [ ] Scope Delete Endpoint
